---
apiVersion: v1
kind: Namespace
metadata:
  name: developer-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-team-sa
  namespace: developer-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786915780960:role/developer-team-sa-pod-role-prod" # Add created IRSA role arn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-deployment
  namespace: developer-ns
  labels:
    app: developer-s3-access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-s3-access
  template:
    metadata:
      labels:
        app: developer-s3-access
    spec:
      serviceAccountName: developer-team-sa
      containers:
      - name: developer-s3-access
        image: amazon/aws-cli
        command: ["sleep", "infinity"]